### PR TITLE
Fix a bug where an error on request wouldn't propogate.

### LINKED ISSUE #2222: List/Watch fails without error if the list function failse
**Describe the bug**
When listFn returns an error, the ListWatch is broken and no ERROR event is sent

**Client Version**
All

**Server Version**
n/a

**To Reproduce**
Fail the initial list function in a list/watch call.

**Expected behavior**
An error should be emitted to the done handler

See #2217

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #2222

### CODE REVIEW

File: src/cache_test.ts [hunk 1]
```diff
@@ -1460,4 +1460,29 @@ describe('delete items', () => {
...
+        };
+        const lw = new ListWatch('/some/path', fake, listFn);
+        let gotErr: Error | null = null;
+        const errCalled = new Promise<void>((resolve, reject) => {
+            lw.on('error', (err) => {
+                gotErr = err;
+                resolve();
+            });
+        });
+        try {
```
Comment (cjihrig) [inline src/cache_test.ts:1480]: I don't think we need the `try...catch` since the unexpected error will fail the test.

File: src/cache_test.ts [hunk 2]
```diff
@@ -1460,4 +1460,29 @@ describe('delete items', () => {
...
+            await lw.start();
+            await errCalled;
+            equal(gotErr, requestErr);
```
Comment (cjihrig) [inline src/cache_test.ts:1483]: Since we want a `===` check here:
```suggestion
            strictEqual(gotErr, requestErr);
```

**Review by cjihrig — COMMENTED** [review]
Two small nits on the test.

File: src/cache_test.ts (hunk 2 above)
Comment (brendandburns) [reply src/cache_test.ts]: done (and removed the import at the top)

**Comment by brendandburns** [comment]
Comments addressed, please re-check.

Thanks!

**Review by cjihrig — APPROVED** [review]
/lgtm
/approve
