### PR TITLE
fix: apply http agent if needed

### LINKED ISSUE #2348: TypeError: Protocol "http:" not supported. Expected "https:"
So yeah I spent like 2 hours deep dive debugging into this only to discover a bug.

https://github.com/kubernetes-client/javascript/blob/3283cb12f146baf0ced6061d06697a3ecd25917a/src/config.ts#L527-L551

more specifically

https://github.com/kubernetes-client/javascript/blob/3283cb12f146baf0ced6061d06697a3ecd25917a/src/config.ts#L533-L536

if no `proxyUrl` is set, then the default will be an HTTPS agent, which does not work with `kubectl proxy` environments.

### PR DESCRIPTION
**Pull request by mstruebing**
This applies an http agent if needed.
I'm not entirely sure about the security implications of this, but I guess it should be not a problem though.

Fixes #2348

### CODE REVIEW

File: src/config_test.ts [hunk 1]
```diff
@@ -298,7 +299,7 @@ describe('KubeConfig', () => {
         });
     });
 
-    describe('applyHTTPSOptions', () => {
+    describe.only('applyHTTPSOptions', () => {
```
Comment (cjihrig) [inline src/config_test.ts:302]: Can you remove the `only`.

File: src/config.ts [hunk 2]
```diff
@@ -544,6 +545,8 @@ export class KubeConfig implements SecurityAuthentication {
             } else {
                 throw new Error('Unsupported proxy type');
             }
+        } else if (cluster && cluster.server && cluster.server.startsWith('http:')) {
```
Comment (cjihrig) [inline src/config.ts:548]:
```suggestion
        } else if (cluster?.server?.startsWith('http:')) {
```

File: src/config_test.ts (hunk 1 above)
Comment (mstruebing) [reply src/config_test.ts]: oops, leftover.

File: src/config.ts [hunk 3]
```diff
@@ -544,6 +545,8 @@ export class KubeConfig implements SecurityAuthentication {
             } else {
                 throw new Error('Unsupported proxy type');
             }
+        } else if (cluster?.server?.startsWith('http:')) {
```
Comment (brendandburns) [inline src/config.ts:548]: Can we also check for `skipTlsVerify` being `true` before we allow http URLs? It's really not secure to do this.

Comment (mstruebing) [reply src/config.ts]: Pushed a commit to check for `skipTlsVerify` as well and added a test for this.
I agree that it's not secure but I think the library should allow this as it is possible to do. 🤔

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!
