### PR TITLE
Fix sending protocols for web sockets.

### LINKED ISSUE #170: Exec.exec fails on json.parse
Using version 0.7.1 when I run exec which fails (status code 1) I got a valid json on the handler - https://github.com/kubernetes-client/javascript/blob/master/src/web-socket-handler.ts#L47
So the JSON.parse is working as expected. 
Since version 0.7.2 I got a string which  make the JSON.parse to throw.
Here is real example of response from 0.7.1 and 0.7.2
0.7.1:
```js
{
	"metadata": {},
	"status": "Failure",
	"message": "command terminated with non-zero exit code: Error executing in Docker Container: 137",
	"reason": "NonZeroExitCode",
	"details": {
		"causes": [{
			"reason": "ExitCode",
			"message": "137"
		}]
	}
}
```
0.7.2:
```js
"command terminated with non-zero exit code: Error executing in Docker Container: 137"
```

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #170 

@GiladShoham

### CODE REVIEW

File: src/exec.ts [hunk 1]
```diff
@@ -18,7 +19,8 @@ export class Exec {
 
     // TODO: make command an array and support multiple args
     public async exec(namespace: string, podName: string, containerName: string, command: string,
-                      stdout: stream.Writable | any, stderr: stream.Writable | any, stdin: stream.Readable | any,
+                      stdout: stream.Writable | null, stderr: stream.Writable | null, stdin: stream.Readable | null,
+                      statusCallback: (status: V1Status) => void,
```
Comment (itowlson) [inline src/exec.ts]: Is this a breaking change for clients?  Is there anything we can do to make it non-breaking, e.g. make it the last parameter and optional?  (We seem to handle it being `null`, so could also handle it being `undefined`.)

File: src/exec_test.ts [hunk 2]
```diff
@@ -69,7 +72,7 @@ describe('Exec', () => {
             when(fakeWebSocket.connect(`${path}?${args}`, null, anyFunction())).thenResolve(fakeConn);
 
             await exec.exec(
-                namespace, pod, container, cmd, osStream, errStream, isStream, false);
+                namespace, pod, container, cmd, osStream, errStream, isStream, nop, false);
```
Comment (itowlson) [inline src/exec_test.ts]: No new tests for the status handler being called?

File: src/exec.ts (hunk 1 above)
Comment (itowlson) [inline src/exec.ts]: Usage of `statusCallback` is non-obvious, even with the exec sample.  Can we provide any documentation on this?

File: examples/typescript/exec/exec-example.ts [hunk 3]
```diff
@@ -1,9 +1,15 @@
...
+const command = process.argv[2];
 
-let kc = new k8s.KubeConfig();
+const kc = new k8s.KubeConfig();
 kc.loadFromDefault();
 
-let exec = new k8s.Exec(kc);
-exec.exec('default', 'nginx-4217019353-9gl4s', 'nginx', command, process.stdout, process.stderr, process.stdin, true /* tty */);
+const exec = new k8s.Exec(kc);
+exec.exec('default', 'demo', 'demo', command,
```
Comment (drubin) [inline examples/typescript/exec/exec-example.ts]: I think it would be a nice to be able to show the difference between pod/container here. Either via a comment or via the previous example `'nginx-4217019353-9gl4s` shows more clearly its pod

File: src/exec.ts (hunk 1 above)
Comment (brendandburns) [reply src/exec.ts]: Updated so that it's not a breaking change.

File: src/exec_test.ts (hunk 2 above)
Comment (brendandburns) [reply src/exec_test.ts]: Added a test.

File: src/exec.ts (hunk 1 above)
Comment (brendandburns) [reply src/exec.ts]: Added JSDoc.

File: examples/typescript/exec/exec-example.ts (hunk 3 above)
Comment (brendandburns) [reply examples/typescript/exec/exec-example.ts]: reverted.

**Comment by brendandburns** [comment]
@itowlson @drubin I think this is read for another look.

Thanks!

**Comment by drubin** [comment]
@brendandburns It needs a rebase but

/lgtm

File: examples/typescript/exec/exec-example.ts [hunk 4]
```diff
@@ -1,9 +1,17 @@
...
+const exec = new k8s.Exec(kc);
+exec.exec('default', 'nginx-4217019353-9gl4s', 'nginx', command,
+    process.stdout, process.stderr, process.stdin,
+    (status: k8s.V1Status) => {
+        // tslint:disable-next-line:no-console
+        console.log('Exited with status:');
+        // tslint:disable-next-line:no-console
+        console.log(JSON.stringify(status, null, 2));
+    },
+    true /* tty */);
```
Comment (itowlson) [inline examples/typescript/exec/exec-example.ts]: Does this typecheck with the new (backward compatible) parameter order?
