### PR TITLE
Move to tar-fs.

### LINKED ISSUE #2392: BlueOak-1.0.0 license is not approved by CNCF
`package.json` lists several dependencies that are licensed under the `BlueOak-1.0.0` license. That license is not listed as an [approved CNCF license](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#cncf-allowlist-license-policy).

The packages are also not listed in the [exception lists](https://github.com/cncf/foundation/tree/main/license-exceptions).

Are there any plans to resolve this?

Possible ways:
* Get the license added to the CNCF Approved List
* Apply for a CNCF exception for the specific modules
* Ask the maintainer of the modules to add a dual-license for one of the approved licenses
* Replace the dependencies with something else

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #2392

tar-fs only depends on MIT, ISC and Apache 2 licensed dependencies.

### CODE REVIEW

File: src/cp.ts [hunk 1]
```diff
@@ -1,10 +1,12 @@
-import fs from 'node:fs';
+import fs, { rmSync } from 'node:fs';
 import { WritableStreamBuffer } from 'stream-buffers';
-import * as tar from 'tar';
```
Comment (cjihrig) [inline src/cp.ts:3]: There are some linter errors in this file.

File: package.json [hunk 2]
```diff
@@ -72,6 +72,7 @@
         "socks-proxy-agent": "^8.0.4",
         "stream-buffers": "^3.0.2",
         "tar": "^7.0.0",
```
Comment (cjihrig) [inline package.json:74]: `tar` should be removed from this file and `package-lock.json`

**Review by cjihrig — COMMENTED** [review]
Left a couple comments.

I'm good with this approach, but I do think it might be worthwhile to also pursue a license exception for BlueOak. I realize JavaScript isn't the primary language of most CNCF projects, but I would be surprised if this didn't happen again in some CNCF controlled repo. My understanding is that Isaac (the author of all of the packages in #2392) intends to move all of his modules to this license over time, and a lot of those modules are heavily depended on.

File: src/cp.ts (hunk 1 above)
Comment (brendandburns) [reply src/cp.ts:3]: fixed.

File: package.json (hunk 2 above)
Comment (brendandburns) [reply package.json]: fixed.

File: src/cp.ts [hunk 3]
```diff
@@ -1,7 +1,5 @@
-import fs from 'node:fs';
 import { WritableStreamBuffer } from 'stream-buffers';
-import * as tar from 'tar';
-import tmp from 'tmp-promise';
```
Comment (cjihrig) [inline src/cp.ts:4]: Sorry for the back and forth - I think this is the only use of this dependency in the project. If it's removed here, it can be removed from package.json and package-lock.json too.

Comment (brendandburns) [reply src/cp.ts:4]: Done (and removed `ws` also since it is not a direct dependency)

**Review by cjihrig — APPROVED** [review]
Thanks. It's great to remove dependencies.

/lgtm
/approve
