### PR TITLE
makes exec_auth spawn the command asynchronously

### LINKED ISSUE #2044: exec_auth spawns the command synchronously
**Describe the bug**

exec_auth spawns the command synchronously. 

When the exec command sends information to stdout/stderr to inform the user what to do to authenticate, the program is blocked waiting indefinitely, because the spawn is done synchronously.

 

** Client Version **
1.0.0-rc7

** Server Version **

Azure 1.29.9

**To Reproduce**

- Start an Azure cluster with 'Microsoft Entra ID authentication with Kubernetes RBAC' authn & authz
- get the credentials
- do not execute any request to the cluster, so the token is not cached (or you can remove it: `rm ~/.kube/cache/kubelogin/yourID.json`
- make a request to the API
- the program is blocked executing the `kubelogin` app, which is blocked, waiting for the user to authenticate

**Expected behavior**

The call should be done async
bonus: the information provided by kubelogin should be displayed to the user

** Example Code**

```
import { CoreV1Api, KubeConfig } from "@kubernetes/client-node";

const kc = new KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(CoreV1Api);
const result = k8sApi.listNamespace();
```

**Environment (please complete the following information):**
 - OS: MacOS
 - NodeJS Version: v20.15.1
 - Cloud runtime: Azure

**Additional context**

### PR DESCRIPTION
**Pull request by feloy**
This PR makes exec_auth calls `spawn` instead of `spawnSync`.

This is cery useful for a GUI to continue working during the plugin is executed.

Fixes #2044

### CODE REVIEW

File: src/exec_auth.ts [hunk 1]
```diff
@@ -99,15 +99,33 @@ export class ExecAuth implements Authenticator {
...
-        throw new Error(result.stderr.toString('utf8'));
+
+        return new Promise((accept, reject) => {
+            let stdoutData: string = '';
+            let stderrData: string = '';
+
+            const subprocess = this.execFn(exec.command, exec.args, opts);
+
+            subprocess.stdout.on('data', (data: Buffer | string) => {
+                stdoutData += data.toString('utf8');
```
Comment (cjihrig) [inline src/exec_auth.ts:110]: I think the `data.toString('utf8')` line here and on line 114 may be subtly incorrect.

With this logic, chunks are emitted as `Buffer`s, which are then converted to utf8 strings. However, utf8 characters can be multiple bytes, and the `Buffer` based logic does not know anything about that. It's possible that a utf8 character gets split across multiple chunks, which results in the wrong final string.

I would suggest updating this code in one of two ways:
- Do all of the chunk collecting with `Buffer`s and then convert everything to utf8 at once in the `'close'` event.
- Use `subprocess.std{out,err}.setEncoding('utf8')` on line 108 so that Node emits `'data'` events with proper utf8 chunks.

File: src/exec_auth.ts [hunk 2]
```diff
@@ -99,15 +99,33 @@ export class ExecAuth implements Authenticator {
...
-            throw result.error;
-        }
-        if (result.status === 0) {
-            const obj = JSON.parse(result.stdout.toString('utf8')) as Credential;
-            this.tokenCache[user.name] = obj;
-            return obj;
-        }
-        throw new Error(result.stderr.toString('utf8'));
+
+        return new Promise((accept, reject) => {
```
Comment (cjihrig) [inline src/exec_auth.ts:103]:
```suggestion
        return new Promise((resolve, reject) => {
```

File: src/exec_auth.ts [hunk 3]
```diff
@@ -99,15 +99,33 @@ export class ExecAuth implements Authenticator {
...
+            subprocess.stdout.on('data', (data: Buffer | string) => {
+                stdoutData += data.toString('utf8');
+            });
+
+            subprocess.stderr.on('data', (data) => {
+                stderrData += data.toString('utf8');
+            });
+
+            subprocess.on('error', (error) => {
+                throw error;
```
Comment (cjihrig) [inline src/exec_auth.ts:118]: Should this call `reject(error)` instead of throwing? It might also be worth putting `error` in a variable instead and then handling the `resolve()`/`reject()` logic in the `'close'` event so that you don't have to handle the case where the promise is both resolved and rejected.

File: src/exec_auth.ts [hunk 4]
```diff
@@ -99,15 +99,33 @@ export class ExecAuth implements Authenticator {
...
+            });
+
+            subprocess.on('close', (code) => {
+                if (code !== 0) {
+                    throw new Error(stderrData);
```
Comment (cjihrig) [inline src/exec_auth.ts:123]: Instead of throwing, maybe `reject(new Error(stderrData))`.

File: src/exec_auth.ts [hunk 5]
```diff
@@ -99,15 +99,33 @@ export class ExecAuth implements Authenticator {
...
+                }
+                const obj = JSON.parse(stdoutData) as Credential;
```
Comment (cjihrig) [inline src/exec_auth.ts:125]: Since this can throw, consider wrapping it in a `try...catch` and rejecting on error.

File: src/exec_auth.ts (hunk 1 above)
Comment (feloy) [reply src/exec_auth.ts:110]: ok, thanks, I'll change with the second option

File: src/exec_auth.ts (hunk 3 above)
Comment (feloy) [reply src/exec_auth.ts:118]: thanks, I'll change to delay the reject to the `close` event

**Comment by feloy** [comment]
Many thanks for your review. I've made the changes and pushed a new commit

File: src/exec_auth.ts [hunk 6]
```diff
@@ -99,15 +99,46 @@ export class ExecAuth implements Authenticator {
...
+                stdoutData += data.toString('utf8');
+            });
+
+            subprocess.stderr.on('data', (data) => {
+                stderrData += data.toString('utf8');
+            });
+
+            subprocess.on('error', (error) => {
+                savedError = error;
+                throw error;
```
Comment (cjihrig) [inline src/exec_auth.ts:122]: I'm not sure that it still makes sense to throw here.

Comment (feloy) [reply src/exec_auth.ts:122]: my mistake, I forgot to remove it

**Comment by cjihrig** [comment]
LGTM, thanks!

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks for the PR!
